### ISSUE TITLE
Remove the Prisma version check

### ISSUE THREAD

**Issue by xCloudzx** [MichalLytek/typegraphql-prisma#110]
**Is your feature request related to a problem? Please describe.**
It is inconvenient to have to wait for this library to update the (strict) peer dependency version for Prisma to be able to update Prisma. I understand that you can ignore this check with an env variable, but I'm struggling to understand why this exists in the first place. NPM already ensures peer dependencies, which can be overridden with `--force`.

**Describe the solution you'd like**
Remove the version check from the generator.

**Describe alternatives you've considered**
Setting the env variable `SKIP_PRISMA_VERSION_CHECK` to true.

**Additional context**
[Note in README](https://github.com/MichalLytek/typegraphql-prisma#lifting-prisma-version-restriction)
[Prisma version check file](https://github.com/MichalLytek/typegraphql-prisma/blob/5298a246d9e6b078b8977a23b10fe27b50131ce9/src/utils/prisma-version.ts)

**Comment by MichalLytek** [comment]
> I understand that you can ignore this check with an env variable

That's the solution you should use.

> It is inconvenient to have to wait for this library to update the (strict) peer dependency version for Prisma to be able to update Prisma.

For the past year, ~75% of Prisma releases contained breaking changes for the `typegraphql-prisma`.
Disabling this check won't fix your issue, you will just see a stacktrace with `undefined is not a function` instead.

> NPM already ensures peer dependencies

But not everyone uses npm@7, some of them overridde the deps, so that's why I was spammed by bug reports that "it doesn't work with Prisma `2.x.y`".

Rejecting your proposal 🔒
