### ISSUE TITLE
Add support prisma version 3.1.1

### ISSUE THREAD

**Issue by overpod** [MichalLytek/typegraphql-prisma#188]
**Describe the Bug**
It looks like version 3.1.1 is not supported

<img width="1218" alt="Screenshot 2021-09-28 at 07 43 38" src="https://user-images.githubusercontent.com/4576877/135024747-47f3dd49-81a4-4bf4-aea7-91ec96734d54.png">

**Comment by MichalLytek** [comment]
I think I should update the warning message:
https://prisma.typegraphql.com/docs/advanced/prisma-version

**Comment by overpod** [comment]
Many thanks. My question is resolved !!!

**Comment by capaj** [comment]
@MichalLytek wouldn't it be better to require just the same major versions? 
Are we really get into situations when patches and minors are going to break the code generator?

**Comment by MichalLytek** [comment]
> Are we really get into situations when patches and minors are going to break the code generator?

Yes, it's happening really often because DMMF nor generator are not considered public API so they change that without further notice - I mean they have `typegraphql-prisma` inside their tests pipeline so they let me know new version breaks the generator.

Anyway, it has to stay because I don't have time to close 10 issues about "not working with xyz" or "breaks on new Prisma". All you need is to use the env variable if you want experimental features.

**Comment by overpod** [comment]
You can try to do a periodic check using [github action](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows)

**Comment by MichalLytek** [comment]
@overpod New release `v0.16.1` is now compatible with Prisma 3.1.1 🚀 

It contains an improvement in Prisma version check message, which now points to docs website that describe the behavior in details: https://prisma.typegraphql.com/docs/basics/prisma-version

I agree that an ideal solution would be an automatic release mechanism which would be triggered by new Prisma release and that would check if there are any issues with new Prisma release. However, I don't have time to spend on digging into this solution, I think that the env variable workaround solves 99% of issues related to Prisma version check error.
