### ISSUE TITLE
Error: spawn typegraphql-prisma ENOENT

### ISSUE THREAD

**Issue by jakegiri** [MichalLytek/typegraphql-prisma#196]
**Describe the Bug**
When doing prisma generate/migrate it throws this error is thrown at the step of generating :
`Error: spawn typegraphql-prisma ENOENT`

- This error is only throw on the latest version of typegraphql-prisma (v0.16.2), which is designed to work with prisma and @prisma/client of version v3.2.0.
- There is no error when I installed typegraphql-prisma v0.14.8 and respective prima v.2.29.1 

Everything rest is correct in schema.prisma i triple checked it. Also this error is only in the latest version. It works perfectly in the earlier versions

**Comment by BWsix** [comment]
I encountered this "spawn `{package}` ENOENT" problem and managed to solved it by install the `{package}` globally like the prisma package does. Hope this information helps 😳

**Comment by MaxiSantos** [comment]
I had the issue here, silly mistake.. I didn't realize I was using a global instance of prisma althought I was installing latest . I was able to realize about it by enabling debug logs

```bash
export DEBUG="prisma*"; prisma db push
```

I had prisma installed globally, so then I was using `prisma command`. After removing global prisma package and then using `yarn/npx prisma command` then all started to work as expected
